---
- name: Ansible apt module examples
   hosts: 127.0.0.1
   become: true
   tasks:
    - name: Ansible apt-get to get install nginx
      apt:
        name: nginx
        state: absent
        force_apt_get: yes

    - name: Stop service httpd, if started
      ansible.builtin.service:
        name: nginx
        state: stopped
